### ISSUE TITLE
code is not working 

### ISSUE THREAD

**Issue by ahtisham-gsoftconsulting** [himanchau/react-native-book-app#2]
I have some problems with it. On startup, the error 'Unable to resolve module react-navigation-stack'. When I try fix it. Another error appears. 'Exception in HosrFunction: java.lang.AssertionError: illegal type provided'. And then application crashes.

**Comment by himanchau** [comment]
I haven't tested this code on Android. However, here's what I think.

One, probably due the incorrect versions for shared elements, follow here: https://github.com/IjzerenHein/react-navigation-shared-element/blob/navigation-v5/README.md

And them make sure you enable Layout Animation for Android. See here: https://reactnative.dev/docs/layoutanimation

**Comment by prisar** [comment]
in expo android device, app is getting crashed. then, I transferred to an bare rn project. its works fine after reanimated 2 installation.

**Comment by prisar** [comment]
Plus header height have some issue in android. it crashes in release build, but not in debug.

**Comment by boypanjaitan16** [comment]
hey can you please share the bare rn version you made?

**Comment by prisar** [comment]
sure, I am using `0.63.4`.

**Comment by boypanjaitan16** [comment]
I mean something like a repo will be great

**Comment by prisar** [comment]
it's a private project. will try to create a fork of this and share once done.

**Comment by boypanjaitan16** [comment]
I can't appreciate it more, thanks in advance.

**Comment by prisar** [comment]
done. https://github.com/prisar/react-native-book-app

**Comment by himanchau** [comment]
Updated with latest push.
