### ISSUE TITLE
Error while testing with android

### ISSUE THREAD

**Issue by Abhishek12345679** [himanchau/react-native-book-app#3]
I fixed the errors from the previous issue but this is a new error, i think this error occurs due to some issues in the theme.js or possibly the themeing in the App. Note, this error does not appear on ios. 

```
Exception in HostFunction: java.lang.AssertionError: illegal type provided
[native code]
updateProps
[native code]
styleUpdater
```

can you try testing it on android?

**Comment by HERYORDEJY** [comment]
@Abhishek12345679 @himanchau Have you been able to resolve it. Also facing the same error

**Comment by himanchau** [comment]
Resolved with update.
